apiVersion: app.krestomat.io/v1alpha1
kind: G12e
metadata:
  name: g12e-sample
spec:
  ## graphql-engine host and protocol. Default protocol is 'http'
  graphql_engine_ingress_host: "example.krestomat.io"
  graphql_engine_ingress_protocol: "http"

  ## deploy own database for graphql-engine using postgres
  graphql_engine_database_deploy: true

  ## extra graphql-engine environment variables
  graphql_engine_envvars:
    - name: HASURA_GRAPHQL_ENABLE_CONSOLE
      value: "true"
    - name: HASURA_GRAPHQL_DEV_MODE
      value: "true"
    - name: HASURA_GRAPHQL_ENABLED_LOG_TYPES
      value: startup, http-log, webhook-log, websocket-log, query-log

  ## add environment variables from this list of secrets:
  # graphql_engine_secret_envfrom:
  #   - secretName1
  #   - secretName2
